[package]
name = "babylon-bindings"
version = "0.2.0"
authors = ["Konrad Staniec <KonradStaniec@users.noreply.github.com>"]
edition = "2021"
description = "Bindings for CustomMsg and CustomQuery for the Babylon blockchain"
repository = "https://github.com/babylonlabs-io/bindings"
license = "Apache-2.0"

[dependencies]
cosmwasm-schema = "2.1.4"
cosmwasm-std = "2.1.4"
